spec-version: 0.34.2
name: pirouette
version: 2.0.0
extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - ansi-terminal
  - base >= 4.9 && < 5
  - bytestring
  - containers
  - data-default
  - deriving-compat
  - extra
  - haskell-stack-trace-plugin
  - interpolate
  - megaparsec
  - mtl >= 2.2.2
  - optics-core
  - optics-th
  - parallel
  - parser-combinators
  - prettyprinter
  - QuickCheck
  - tasty
  - tasty-expected-failure
  - tasty-hunit
  - tasty-quickcheck
  - template-haskell
  - text
  - uniplate
  # PureSMT deps
  - process
  - typed-process

library:
  source-dirs: src
  ghc-options: -Wall
    -Wno-orphans

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/unit
    dependencies:
      - pirouette
      - tasty-json-reporter
    ghc-options: -threaded

# executables:
#   spec-prof:
#     main: Spec.hs
#     source-dirs:
#       - tests/unit
#     dependencies:
#       - pirouette
#     ghc-options:
#       -threaded
#       -fprof-auto
#       -fexternal-interpreter
#       "-with-rtsopts=-N -p -s -h"
