name: HLint
description: Run HLint on the codebase

inputs:
  directories:
    description: The directories to run HLint on, formatted as a list of JSON strings
    required: true
    default: '["src/", "tests/"]'

runs:
  using: composite
  steps:
    - name: Set up HLint
      uses: haskell/actions/hlint-setup@v2

    - name: HLint src
      uses: haskell/actions/hlint-run@v2
      with:
        path: ${{ inputs.directories }}
        fail-on: warning
