name: Cabal

on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  # TODO: Add a linting/formatting job to run in parallel
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: haskell/actions/setup@v2
      id: setup-haskell-build-env
      with:
        ghc-version: '9.0.2'

    - name: Cache Cabal build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.setup-haskell-build-env.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-cabal-ghc902-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-cabal-ghc902

    # Build
    - name: Build library pirouette
      run: cabal build --verbose pirouette
    
    - name: Build tests pirouette
      run: cabal build --verbose spec

    # Test
    - name: Run tests pirouette
      run: cabal run spec -- --json-path out.json --markdown-path $GITHUB_STEP_SUMMARY
